### ISSUE TITLE
Apply for verification on AlgoExplorer

### ISSUE THREAD

**Issue by SCN9A** [asastats/channel#104]
https://medium.com/randlabs/how-do-i-verify-my-asset-or-application-with-algoexplorers-login-system-for-creators-2a3db8321333

May 23rd
> Launching today in conjunction with our new reputation system, is a Login system for Creators which allows project owners to update their asset’s or application’s information directly on AlgoExplorer. This new system will allow them to also apply for verification directly on the platform.

**Comment by ipaleka** [comment]
So nothing has changes, we have got that neutral status:
![algoexplorer](https://user-images.githubusercontent.com/49662536/170388833-ed043c06-e0ca-499b-9826-34b4068f6554.png)

Here's the explanation:
![reputation](https://user-images.githubusercontent.com/49662536/170388942-06daba2c-f848-4a21-a3a6-0816571c0c07.png)

How we can get that Notable status?

**Comment by ipaleka** [comment]
Re: 393537671 ASA Stats Token Proposal Accepted!

Hello!

I received the email quoted below to the address connected with my GitHub account, so I wanted to move the discussion here under the @asastats.com email.

I used this address in the first successful verification process and afterward I made a contact with Erik about the updated logo.

Also, there's a note in the quoted email below about our new asset badge. I can see the blue badge next to our creator address in the profile page, while the asset doesn't show one on the ASA Stats Token public page.

I wanted to ask how can we qualify for the Notable status?

- - - - -
Notable Status
Projects that are widely recognized by the community and have maintained a healthy reputation for at least 3 months.
- - - - -

We can surely provide evidence about the healthy reputation the ASA Stats project in general and the ASA Stats Token have got in the last 6 months.

Sincerely,

Ivica


 ---- On Wed, 25 May 2022 16:48:40 +0200 Algoexplorer <[\*@\*](mailto:\*@\*)> wrote ----
 > ASA Stats Token 393537671            Congrats! 🎉                                Your request for asset verification has been processed succesfully,            congratulations!                          Checkout your new asset badge on              AlgoExplorer
 > ASSET OVERVIEW
 > Made with 💙 from            Rand Labs
 > Have doubts or want to contact us?

**Comment by ipaleka** [comment]
Our page on Algo Explorer is updated:

![algoexplorer](https://user-images.githubusercontent.com/49662536/172280418-270ce66e-fe4d-4ddd-9c09-b1274e263181.png)

I'm about to close this issue and would open another if we get information for applying for Notable status. Here's the email correspodence:

- - - - -

Hello Ivica,

If you are asking about the 3-month window requirement, it refers to 3 months since the token was created on AlgoExplorer, not since it reached neutral status.

Kind regards,

- - - - -

Hello \*\*!

Thanks for your response and for the updated ASA Stats Token page on Algo Explorer. :)

May you please provide some guidelines for us to apply for that Notable status?

Best regards,

Ivica

**Comment by ipaleka** [comment]
Hello Ivica,

Hope all is well. You can read about the requirements for each tier here: https://algoexplorer.io/reputation-system.

Kind regards,
