### ISSUE TITLE
Refresh button in the CSV export page doesn't work

### ISSUE THREAD

**Issue by nyanez1976** [asastats/channel#1079]
Bug description: Hi, trying to update my report and it will not reset. I hit the refresh button and nothing happens.

**Comment by ipaleka** [comment]
Thanks for your report!

The issue is partially resolved, or at least the initial checks confirmed that. Please try to open another session (like in a new private/incognito window) and try to click the Refresh button from there.

**Comment by ipaleka** [comment]
As we have moved the engine to another server, the initial setup is no longer an optimal solution and we'd probably change it.

**Comment by ipaleka** [comment]
> Bug description: Hi, trying to update my report and it will not reset. I hit the refresh button and nothing happens.

Hi @nyanez1976 ! We need your public Algorand address in order to allocate rewards in ASASTATS to you after [this issue is processed](https://github.com/asastats/channel/discussions/1116). If you don't want to expose the address publicly, please send it in DM on Discord to @ipaleka or on Reddit to @hopemeetme . Make sure you opted in to ASA Stats Token, ID: 393537671

**Comment by nyanez1976** [comment]
Thanks4S5UQDMUP3WW34JBYNBI4AB3KML34ZFB6XBHPN7QF36IZMROJYXGVMTXOISent from my iPhoneOn Nov 24, 2024, at 5:36 AM, Ivica Paleka ***@***.***> wrote:﻿

Bug description: Hi, trying to update my report and it will not reset. I hit the refresh button and nothing happens.

Hi @nyanez1976 ! We need your public Algorand address in order to allocate rewards in ASASTATS to you after this issue is processed. If you don't want to expose the address publicly, please send it in DM on Discord to @ipaleka or on Reddit to @hopemeetme . Make sure you opted in to ASA Stats Token, ID: 393537671
