### ISSUE TITLE
Some ASA are missing links to their project's page

### ISSUE THREAD

**Issue by moloch10** [asastats/channel#125]
Missing
310014962 ALCH: https://www.alchemon.net/
403499324 GP: https://nexusasa.com/
559219992 OCTO: https://octorand.com/
226701642 YLDY: https://yieldly.finance/

Also, the ones that have a link do not render them consistently, e.g.
542132831 APF > URL: https://www.asaportfolio.com/
470842789 DEFLY > URL: defly.blockshake.io
287867876 OPUL > URL: https://opulous.org/
511484048 STKE > URL: www.algostake.org
329110405 Tacos > URL: Dorastacos.com

**Comment by ipaleka** [comment]
This is probably the oldest "issue" we have got:

by ipaleka in [Discord](https://discord.com/channels/906917846754418770/909142143254269972/909159325036060702) on 11/13/2021:

- - - - -

@GamingToups and @Mikeyy raised an issue of wrong URLs in ASA initial configuration transaction.
 
https://discord.com/channels/906917846754418770/908054330265960478/908369331308601448
https://discord.com/channels/906917846754418770/908054330265960478/908762373299507200

Probably the optimal solution for that would be a repository on its own, created under ASA Stats GitHub organization https://github.com/asastats .

The best explanation is by example, so here's a link to Tinyman's repo for ASA icons, and we could follow the similar principles, only for URLs instead of icons: https://github.com/tinymanorg/asa-list.

Everyone, any thoughts on this? What should be the name of such repository (the URL will be https://github.com/asastats/reponame) ? 

- - - - -

https://trello.com/c/NkxPXvKy/19-github-subproject-for-updated-urls-needs-a-contributor

- - - - -

And a bunch of other comments pointing to the same resolution...

So, the solution is defined, we just need someone who will start with it.

**Comment by ipaleka** [comment]
https://github.com/asastats/channel/discussions/126
