### ISSUE TITLE
[CT3] Add glossary to documents

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#41]
[CT3] dankster1

Add explanations for (technical) terms used in all documents for easier understanding. We could probably create [a wiki page](https://github.com/asastats/channel/wiki) and link it at the end of those documents.

https://discord.com/channels/906917846754418770/915342738201931836/948306867958988860
> I want to suggest if possibly we can have glossary (explaining some technical terms) at the end of each documents, this will further buttress 'our great user experience goal'

> This will give users/readers better understanding of our documents hence a better understanding of ASA Stats project.

- - - - -
> So - I'm wondering if you have specific documents in mind to target - as well, what terms you'd have in mind to add to the glossary, etc.  What is the scope here?

> I really do not have specific document(s) in mind although recently I checked FAQ and ABOUT PAGE document which prompted the
> I am convinced if it work for one docs it definitely will work for others. 
> Just like how glossary in text enable us to understand the difficult or technical terms in simpler words. 

> Ẹxample of such words in my opinion are :

> AMM, DAO, damo etc.

**Comment by DanksterASAStats** [comment]
# ASA (Algorand Standard Assets)

**ASA:**
Stands for Algorand Standard Assets. ASAs are on-chain assets that benefit from the same security, compatibility, speed, and ease of use as the Algo. ASAs can represent stablecoins, loyalty points, system credits, in-game points, and more.

**ASA Stats Token:**
Is an Algorand Standard Asset which is a type of on-chain asset. ASA Stats is considered a utility token.

# API (Application Programming Interface)

**API:**
An API (Application Programming Interface) is a set of rules and specifications that allow software to communicate with other applications, services, or data. APIs can also be used to build and integrate application software.

**API Access:**
The process of allowing mobile apps, developers' frameworks, building management tools, and software applications to access and use pertinent data from a given API. ASA Stats project will offer limited to comprehensive API access in subscription tiers. Subscribers will have an option to:
- **Develop ASA Stats User Widgets** by leveraging ASA Stats API services to develop advanced user widgets for use in the portfolio view.
- **Develop their Own Software Solutions** by leveraging ASA Stats API services to develop ready-to-use software tools for service providers and software companies.

**API Keys:**
Can be obtained to access ASA Stats API services. Subscribers to Asastatser & Professional tiers get API access with decreased bandwidth (Rate-Limited). Unlimited access is reserved for Cluster tier.

**API Endpoints:**
An API endpoint is a digital location on a server where an API receives requests for a specific resource. ASA Stats project will offer API endpoint access in limited to comprehensive subscription tiers.

# DAO (Decentralized Autonomous Organization)

**DAO:**
A Decentralized Autonomous Organization (DAO) is a type of organization governed by a computer program encoded with rules and not controlled by a central authority. DAOs are member-owned communities that use blockchain technology and smart contracts to operate and are designed to be transparent and autonomous. ASA Stats project seeks to establish a DAO in a subsequent phase of project development.

# Utility Token

**Utility Token:**
Utility tokens are a special kind of virtual currency that resides on its own blockchain and gives access to the specialized products or services the company is working on. ASA Stats Token is a utility token used for accessing ASA Stats professional services, governance, and staking.

# Widget

**Widget:**
A widget is a part of a GUI (Graphical User Interface) that displays information or allows a user to interact with an application or operating system (OS). Widgets can include buttons, icons, pull-down menus, selection boxes, progress indicators, scroll bars, and more. For example:
- On a Windows desktop, widgets are small cards that display dynamic content from apps and services.
- On an iPhone, widgets can provide a quick view of information like the weather, battery level, reminders, and headlines.

ASA Stats project will offer access to useful widgets in subscription tiers. Subscribers to the Professional and Cluster tiers can develop and publish advanced user widgets for use in the portfolio view. These widgets must pass an audit by the ASA Stats Team. An external audit may be required.

**Trading User Widget:**
Experience unified trading excellence with the ASA Stats trading widget. Users can add any ASA to the trading widget in full or partially to utilize trading functionalities: Buy/sell, stake, remove liquidity.

**Publish ASA Stats User Widgets:**
Create and publish your own ASA Stats user widget. These widgets must pass an audit by the ASA Stats Team. An external audit may be required too.

**Order Development of a Widget:**
ASA Stats will develop or sponsor the development of a user widget that brings functionality not available in the existing set of user widgets. This service is limited to Cluster tier subscribers only.

**Innovative Features:**
ASA Stats strives to enhance user experience by incorporating innovative features. A list of user widgets desired by the ASA Stats community demonstrates an array of possibilities for future development.

# Domain

**Custom Domain:**
Custom domain options are available.

# Kubernetes Cluster

**Kubernetes Cluster:**
A group of computing nodes, or worker machines, that run containerized applications. Containerization is a software deployment and runtime process that bundles an application's code with all the files and libraries it needs to run on any infrastructure.

**Dedicated Kubernetes Cluster:**
A dedicated Kubernetes cluster is a cluster that is purpose-built for a single application or workload and is dedicated to a single tenant.

# Subscription Model

**Subscription Model:**
A subscription business model is a payment model in which customers pay a recurring fee in exchange for access to a product. ASA Stats project has 2 subscription models: the User Subscription Model and the DAO Governors Model. Each model provides access to 4 tiers of functionality:
- **Intro**
- **Asastatser**
- **Professional**
- **Cluster**

**User Subscription Model:**
A user subscription is a recurring payment made by a user for access to a product or service. ASA Stats subscribers may choose to purchase a specified amount of ASA Stats Token on a monthly basis for the tier of access respective to the level of functionality they require.

**DAO Governors Model:**
ASA Stats DAO governors are granted access to ASA Stats subscription benefits without the need to pay recurring monthly subscription fees. The subscription privileges are immediate upon staking and last for as long as a user stakes ASA Stats. Currently, there is an incentive for users who stake ASA Stats for 10 months to become a DAO Governor. Governor seats last forever.

**Governance Seat:**
A DAO Governor's privilege to own a stake in ASA Stats. The governance seat (which lasts forever) is conditional — at least ten months of staking has to pass — while the subscription benefits last for as long as a user stakes ASA Stats.

**Governance Seat Votes:**
Shape the future of ASA Stats. DAO subscription tiers grant a number of votes defined by the tier.

**Governor Seat's Votes Upgrade:**
Increase your voting power and privileges. User's account is automatically upgraded to the next tier once ASA Stats staked reaches the minimum amount of the next tier. The governance votes update takes place exactly a year after.

**DAO Kubernetes Node:**
All DAO governors will share the resources of the DAO Kubernetes Node, except for Cluster tier subscribers who get a dedicated Kubernetes node.

**Governance Staking:**
Earn ASA Stats. Staking rewards are available on a first-come, first-served basis, while supplies last; early adopters are encouraged to participate. Stake ASA Stats on Cometa and grab your governance seat.

**Damo:**
ASA Stats uses the damo measurement when discussing rewards. One damo is equal to 1,000,000 ASA Stats Tokens.

# Algorand Data Integration

**Algorand Data Integration:**
ASA Stats integrates data seamlessly from the Algorand blockchain, prioritizing 100% uptime reliability. It minimizes reliance on third-party SDKs, utilizing providers' SDKs only when necessary for specific functionalities.

# Selling Price Optimisation

**Selling Price Optimisation:**
ASA Stats brings the maximum value engine to users' assets by calculating the maximum value of the ASAs held in their wallet(s), as well as the optimal amounts that would be sold on each of the AMMs or DEXes.

# NFT Pricing Model

**NFT Pricing Model:**
ASA Stats builds a deep learning model to assess NFT prices. The model is continuously updated and refined, derived from a dataset containing millions of records.

# User Bundles

**User Bundles:**
Create and save bundles of Algorand addresses in the user settings, with the ability to edit and change the addresses in a bundle.

**Bundled Addresses:**
Track the current assets value for any wallet address on the Algorand blockchain; up to X number of addresses combined, based on subscription tier or DAO status.

**Bundle Naming:**
Create a custom name for each of your user bundles.

**Bundle URL:**
Get a custom URL for every user bundle. URL access could be private or public based on subscription tier or DAO status.

# Markdown

**Markdown:**
Markdown is a lightweight markup language that you can use to add formatting elements to plaintext text documents.

# Additional Terms

**LP (Liquidity Provider):**
In the context of decentralized finance (DeFi), an LP is an individual or entity that supplies assets to a liquidity pool on a decentralized exchange (DEX) in exchange for a portion of the trading fees.

**Yield Farming:**
Yield Farming is a practice in DeFi where users stake or lend their cryptocurrency assets in order to earn returns or rewards. This usually involves providing liquidity to liquidity pools or participating in staking programs.

**Impermanent Loss:**
Impermanent Loss occurs when the value of assets in a liquidity pool diverges from the value of those assets if they were simply held in a wallet. This loss is "impermanent" because it can be recovered if the relative prices of the assets return to their original values.

**Slippage:**
Slippage refers to the difference between the expected price of a trade and the actual price at which the trade is executed. This can occur due to market volatility or low liquidity, resulting in a less favorable price for the trader.

**DEX (Decentralized Exchange):**
A Decentralized Exchange is a type of cryptocurrency exchange that operates without a central authority, allowing users to trade directly with each other using smart contracts on a blockchain.

**CEX (Centralized Exchange):**
A Centralized Exchange is a type of cryptocurrency exchange that is operated by a centralized company or entity. Users trade through the platform, which acts as an intermediary.

**Bridge:**
In the context of blockchain, a bridge refers to a technology that allows the transfer of assets or data between two different blockchain networks. This helps enhance interoperability between different blockchain ecosystems.

**Stablecoin:**
A Stablecoin is a type of cryptocurrency designed to have a stable value by being pegged to a reserve asset like a fiat currency (e.g., USD

**Comment by ipaleka** [comment]
Hello, welcome to our GitHub and thank you for your effort, great job, that's exactly what we need. :)

Right now, the comment is hard to read, if you can please format your comment so it can be easier for people to read.

Both GitHub and Discord may use markdown (another term to explain for our users :) ), so if you can prefix each term by for example three # and put the description in the following row, like:

```
### Damo
ASA Stats uses the damo measurement when discussing rewards. One damo is equal to 1,000,000 ASA Stats Tokens.

```
which renders to:

### Damo
ASA Stats uses the damo measurement when discussing rewards. One damo is equal to 1,000,000 ASA Stats Tokens.

Also, it would be nice to include some hyperlinks in a form of `[ASA Stats website](https://www.asastats.com)` which renders to [ASA Stats website](https://www.asastats.com).

P.S. Under ASA, we'd need an exact description of Algorand Standard Asset, not just ASA Stats Token.

**Comment by kerrilija** [comment]
Well done @DanksterASAStats ! :)
