### ISSUE TITLE
Some NFTs are again "not evaluated" even though they were listed properly for a bit

### ISSUE THREAD

**Issue by moloch10** [asastats/channel#444]
Bug description:

Both [796490640](https://algoexplorer.io/asset/796490640) & [711286913](https://algoexplorer.io/asset/711286913) used to be fine, now they're not.

In addition, the new Tinygear NFT is also not evaluated: [1009078085](https://algoexplorer.io/asset/1009078085)

What's interesting is that with these three, all have an error when trying to open on nftexplorer.app but are fine on algoexplorer.io.

Here's sample links to each platform:
[1009078085 on nftexplorer.app](https://www.nftexplorer.app/asset/1009078085)
[1009078085 on algoexplorer.io](https://algoexplorer.io/asset/1009078085)

**Comment by ipaleka** [comment]
That *for a bit* was before the new NFT engine update.

In order to qualify for an NFT we have defined a total supply limit of 20000 (more or less based on Pera's NFT).

A total supply of 420,000,000,000 ([796490640](https://algoexplorer.io/asset/796490640)) IMO definitely disqualifies an ASA from being an NFT.

https://algoexplorer.io/asset/711286913 has a total supply of 100,000 and we can hard code an exception for it, just the way we did for CupStakes.

Are you ok with that?

**Comment by moloch10** [comment]
> In order to qualify for an NFT we have defined a total supply limit of 20,000 (more or less based on Pera's NFTs).
> 
> A total supply of 420,000,000,000 ([796490640](https://algoexplorer.io/asset/796490640)) IMO definitely disqualifies an ASA from being an NFT.

Ok yeah, this one is more their community token for raffles and discord games.

I checked the new [Tinygear](https://algoexplorer.io/asset/1009078085) total supply and it's at 30K total supply.

> https://algoexplorer.io/asset/711286913 has a total supply of 100,000 and we can hard code an exception for it, just the way we did for CupStakes.
> 
> Are you ok with that?

It's your call really. If you don't mind adding exceptions ... although it might be easier to up the 20K.

**Comment by ipaleka** [comment]
> It's your call really. If you don't mind adding exceptions ... although it might be easier to up the 20K.

I guess increasing those 20 is a way to start down the slippery slope - there's no limit then - and I'd rather adding the exceptions...
