### ISSUE TITLE
[Internal] Research and implement FIFA+ Collect exporting

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#700]
It looks like it is possible to transfer out FIFA+ Collect NFTs from the custody account.

**Comment by kerrilija** [comment]
Btw. from Walix @ FIFA+ Collect unofficial Telegram Group:

> Unfortunately, the self custody feature contains breaking changes for fifapluscollect.info  (including the website and the Telegram and Twitter bots).
Fixing it requires significant development time, which I don't have at the moment.
Since it's unlikely that I will find that time in the following weeks, all services get discontinued until further notice.
I really regret to make this announcement but I have no other choice.
Thank you everyone for understanding..

**Comment by ipaleka** [comment]
https://twitter.com/FIFAPlusCollect/status/1678785168775979008

**Comment by ipaleka** [comment]
This was an internal issue in our case, the engine has been just slightly changed to not accumulate exports as failed purchases. From users perspective all stays the same.
