### ISSUE TITLE
NFTs received from Exa's loot boxes show mixed results

### ISSUE THREAD

**Issue by moloch10** [asastats/channel#749]
I opened one of Exa's boxes and Stats shows a last purchase price of 0 but the date is of the actual last sales transaction.

![image](https://github.com/asastats/channel/assets/97535612/ac9c895b-9e7c-47ed-b333-ab1b7ee6a24a)

From nftx:

![image](https://github.com/asastats/channel/assets/97535612/fcd196e3-a7a9-4dca-9b7a-7bd7b3143211)

**Comment by ipaleka** [comment]
Loot boxes haven't even been researched, so the correct time is excellent news. :)

**Comment by ipaleka** [comment]
So, EXA Lootboxes functionality is deployed. If applicable, NFTs received from opened EXA Lootbox NFTs (L1, L2, and L3) are correctly recorded as last purchases. Still, the price is 0 ALGO because NFT beta engine with prices for NFTs hasn't been deployed yet - our system records that the purchase cost was for example 1 EXA Lootbox NFT L2, but that evaluates to 0 ALGO for now.
