### ISSUE TITLE
[F2] Messina.one Liquid Staking - Research and decide about implementation

### ISSUE THREAD

**Issue by kerrilija** [asastats/channel#764]
Users get 1 mALGO on every staked ALGO. Tokens are not being locked in a smart contract.

https://messina.one/liquid-staking

**Comment by ipaleka** [comment]
As a side note, their asset has been deployed as a new Algorai bear yield asset. https://github.com/asastats/channel/issues/767

Algorai deploys deposit apps on Fridays, so it's expected that mAlgo deposit app for week 1 will come this Friday.

**Comment by ipaleka** [comment]
### Research report

The process consists of three phases:

1) stake ALGO
2) request unstake
3) claim

1)
Let's first explain this "staking".  @kerrilija you're right that those ALGO aren't locked in a smart contract in a *regular* way, they just mint mAlgo and send them back to you. You're able to "unstake" any amount of mAlgo you get in your account, no matter if you get it through their staking or on the open market,

Nevertheless, in this staking phase you get 1:1 mAlgo in return. Our engine currently evaluates 1 mAlgo to 0.997483 ALGO and I suppose we shouldn't complicate things and we should leave it as is.

2)
This is the step where we can do something, but the problem is that there's no actual trace available (at least I couldn't find it with the initial research). They do record a pending withdrawal in the app's box, but it isn't connected to an address.

In order to present such information we should power up the indexer and have a ledger that calculates every address state.  That would have been our approach afaic if the claim wasn't available immediately (like they suggest with that "in the next 6 hours" note), but the thing is that you can claim the very next block.

3)
After you claim there's nothing to do else.

-----

So, my opinion is that when the bull market comes again and when the ecosystem recovers we should implement a ledger-like system that would power up the indexer and check the state of the addresses that hit their dApp. Before that afaic that is too much hassle for something maybe nobody will ever notice (because all of them will immediately claim).

**Comment by AlgoRhythMatic** [comment]
@kerrilija, @ipaleka - assuming IC1 for the creation here, but would you consider the feature portion F1 or F2 or something else (was not sure if there was research involved)?

**Comment by ipaleka** [comment]
Yes, @kerrilija did the initial research and therefore F2 is set, tnx for the remainder! :)
